import { useEffect, useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/contexts/AuthContext";
import { Plus, Search } from "lucide-react";
import { addMonths, format } from "date-fns";

export default function Transactions() {
  const [transactions, setTransactions] = useState<any[]>([]);
  const [showCreate, setShowCreate] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [rates, setRates] = useState<any[]>([]);
  const { user, role, branchId } = useAuth();
  const { toast } = useToast();

  // Form state
  const [customerName, setCustomerName] = useState("");
  const [customerNic, setCustomerNic] = useState("");
  const [customerAddress, setCustomerAddress] = useState("");
  const [customerPhone, setCustomerPhone] = useState("");
  const [itemDescription, setItemDescription] = useState("");
  const [itemWeight, setItemWeight] = useState("");
  const [itemKarat, setItemKarat] = useState("24");
  const [appraisedValue, setAppraisedValue] = useState("");
  const [loanAmount, setLoanAmount] = useState("");
  const [selectedRateId, setSelectedRateId] = useState("");
  const [periodMonths, setPeriodMonths] = useState("6");
  const [remarks, setRemarks] = useState("");
  const [loading, setLoading] = useState(false);

  const fetchTransactions = async () => {
    let query = supabase.from("pawn_transactions").select("*").order("created_at", { ascending: false });
    if (branchId && role !== "SUPERADMIN" && role !== "ADMIN") query = query.eq("branch_id", branchId);
    if (statusFilter !== "all") query = query.eq("status", statusFilter);
    if (searchQuery) {
      query = query.or(`customer_name.ilike.%${searchQuery}%,customer_nic.ilike.%${searchQuery}%,pawn_id.ilike.%${searchQuery}%`);
    }
    const { data } = await query;
    if (data) setTransactions(data);
  };

  const fetchRates = async () => {
    const { data } = await supabase.from("interest_rates").select("*").eq("is_active", true);
    if (data) setRates(data);
  };

  useEffect(() => { fetchTransactions(); fetchRates(); }, [searchQuery, statusFilter]);

  const selectedRate = rates.find((r) => r.id === selectedRateId);

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!branchId) { toast({ title: "Error", description: "No branch assigned", variant: "destructive" }); return; }
    setLoading(true);
    try {
      const maturityDate = format(addMonths(new Date(), parseInt(periodMonths)), "yyyy-MM-dd");
      const ratePercent = selectedRate?.rate_percent || 0;
      
      const { error } = await supabase.from("pawn_transactions").insert({
        pawn_id: "", // Auto-generated by trigger
        branch_id: branchId,
        customer_name: customerName,
        customer_nic: customerNic,
        customer_address: customerAddress || null,
        customer_phone: customerPhone || null,
        item_description: itemDescription,
        item_weight_grams: parseFloat(itemWeight),
        item_karat: parseInt(itemKarat),
        appraised_value: parseFloat(appraisedValue),
        loan_amount: parseFloat(loanAmount),
        interest_rate_id: selectedRateId || null,
        interest_rate_percent: ratePercent,
        period_months: parseInt(periodMonths),
        maturity_date: maturityDate,
        remarks: remarks || null,
        created_by: user!.id,
      });
      if (error) throw error;
      toast({ title: "Transaction created" });
      setShowCreate(false);
      resetForm();
      fetchTransactions();
    } catch (error: any) {
      toast({ title: "Error", description: error.message, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  const resetForm = () => {
    setCustomerName(""); setCustomerNic(""); setCustomerAddress(""); setCustomerPhone("");
    setItemDescription(""); setItemWeight(""); setItemKarat("24"); setAppraisedValue("");
    setLoanAmount(""); setSelectedRateId(""); setPeriodMonths("6"); setRemarks("");
  };

  const updateStatus = async (id: string, status: string) => {
    await supabase.from("pawn_transactions").update({ status }).eq("id", id);
    fetchTransactions();
    toast({ title: `Status updated to ${status}` });
  };

  const statusBadge = (s: string) => {
    if (s === "Active") return "default";
    if (s === "Completed") return "secondary";
    return "destructive";
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Pawn Transactions</h1>
        {(role !== "STAFF" || role === "STAFF") && branchId && (
          <Button onClick={() => setShowCreate(true)}><Plus className="mr-2 h-4 w-4" /> New Transaction</Button>
        )}
      </div>

      <div className="flex gap-4">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
          <Input placeholder="Search by name, NIC, or Pawn ID..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} className="pl-9" />
        </div>
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-40"><SelectValue /></SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Status</SelectItem>
            <SelectItem value="Active">Active</SelectItem>
            <SelectItem value="Completed">Completed</SelectItem>
            <SelectItem value="Defaulted">Defaulted</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <Card>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Pawn ID</TableHead>
                <TableHead>Customer</TableHead>
                <TableHead>NIC</TableHead>
                <TableHead>Loan Amount</TableHead>
                <TableHead>Rate %</TableHead>
                <TableHead>Maturity</TableHead>
                <TableHead>Status</TableHead>
                {(role === "MANAGER" || role === "SUPERADMIN" || role === "ADMIN") && <TableHead>Actions</TableHead>}
              </TableRow>
            </TableHeader>
            <TableBody>
              {transactions.map((t) => (
                <TableRow key={t.id}>
                  <TableCell className="font-mono font-medium">{t.pawn_id}</TableCell>
                  <TableCell>{t.customer_name}</TableCell>
                  <TableCell>{t.customer_nic}</TableCell>
                  <TableCell>{Number(t.loan_amount).toLocaleString()}</TableCell>
                  <TableCell>{t.interest_rate_percent}%</TableCell>
                  <TableCell>{t.maturity_date}</TableCell>
                  <TableCell><Badge variant={statusBadge(t.status) as any}>{t.status}</Badge></TableCell>
                  {(role === "MANAGER" || role === "SUPERADMIN" || role === "ADMIN") && (
                    <TableCell>
                      <Select onValueChange={(v) => updateStatus(t.id, v)}>
                        <SelectTrigger className="w-28 h-8"><SelectValue placeholder="Update" /></SelectTrigger>
                        <SelectContent>
                          <SelectItem value="Active">Active</SelectItem>
                          <SelectItem value="Completed">Completed</SelectItem>
                          <SelectItem value="Defaulted">Defaulted</SelectItem>
                        </SelectContent>
                      </Select>
                    </TableCell>
                  )}
                </TableRow>
              ))}
              {transactions.length === 0 && (
                <TableRow><TableCell colSpan={8} className="text-center text-muted-foreground py-8">No transactions found</TableCell></TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      <Dialog open={showCreate} onOpenChange={setShowCreate}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader><DialogTitle>New Pawn Transaction</DialogTitle></DialogHeader>
          <form onSubmit={handleCreate} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div><Label>Customer Name</Label><Input value={customerName} onChange={(e) => setCustomerName(e.target.value)} required /></div>
              <div><Label>NIC</Label><Input value={customerNic} onChange={(e) => setCustomerNic(e.target.value)} required /></div>
              <div><Label>Address</Label><Input value={customerAddress} onChange={(e) => setCustomerAddress(e.target.value)} /></div>
              <div><Label>Phone</Label><Input value={customerPhone} onChange={(e) => setCustomerPhone(e.target.value)} /></div>
            </div>
            <hr />
            <div className="grid grid-cols-2 gap-4">
              <div><Label>Item Description</Label><Input value={itemDescription} onChange={(e) => setItemDescription(e.target.value)} required /></div>
              <div><Label>Weight (grams)</Label><Input type="number" step="0.01" value={itemWeight} onChange={(e) => setItemWeight(e.target.value)} required /></div>
              <div><Label>Karat</Label>
                <Select value={itemKarat} onValueChange={setItemKarat}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>{[24,22,21,18,14].map((k) => <SelectItem key={k} value={String(k)}>{k}K</SelectItem>)}</SelectContent>
                </Select>
              </div>
              <div><Label>Appraised Value</Label><Input type="number" step="0.01" value={appraisedValue} onChange={(e) => setAppraisedValue(e.target.value)} required /></div>
            </div>
            <hr />
            <div className="grid grid-cols-2 gap-4">
              <div><Label>Loan Amount</Label><Input type="number" step="0.01" value={loanAmount} onChange={(e) => setLoanAmount(e.target.value)} required /></div>
              <div><Label>Interest Rate</Label>
                <Select value={selectedRateId} onValueChange={setSelectedRateId}>
                  <SelectTrigger><SelectValue placeholder="Select rate" /></SelectTrigger>
                  <SelectContent>
                    {rates.map((r) => <SelectItem key={r.id} value={r.id}>{r.name} - {r.rate_percent}%</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <div><Label>Period (months)</Label>
                <Select value={periodMonths} onValueChange={setPeriodMonths}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>{[3,6,9,12,18,24].map((m) => <SelectItem key={m} value={String(m)}>{m} months</SelectItem>)}</SelectContent>
                </Select>
              </div>
            </div>
            <div><Label>Remarks</Label><Textarea value={remarks} onChange={(e) => setRemarks(e.target.value)} /></div>
            <Button type="submit" className="w-full" disabled={loading}>{loading ? "Creating..." : "Create Transaction"}</Button>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}
